ALTER TABLE promos ADD COLUMN IF NOT EXISTS type VARCHAR(10) DEFAULT 'VOUCHER' NOT NULL;
ALTER TABLE promos ADD COLUMN IF NOT EXISTS start_date TIMESTAMPTZ;
ALTER TABLE promos ADD COLUMN IF NOT EXISTS end_date TIMESTAMPTZ;

UPDATE promos SET type = CASE WHEN event_id IS NOT NULL THEN 'PROMO' ELSE 'VOUCHER' END WHERE event_id IS NOT NULL;
